name: build

on:
  push:
  pull_request:

jobs:
  windows:
    name: Windows
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4

      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

  macos:
    name: macOS
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release
